services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /home/houdini/beszel/beszel_data:/beszel_data
      - /home/houdini/beszel/beszel_socket:/beszel_socket
  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/houdini/beszel/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/dev-disk-by-uuid-0690e9fe-6a27-4996-832c-be833cab6446/.beszel:/extra-filesystems/md0:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      DISABLE_PASSWORD_AUTH: true
      USER_CREATION: true
      SHARE_ALL_SYSTEMS: true
      KEY: ${KEY}
networks: {}
