services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /home/houdini/homarr:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=617b3e55112091b2eebdd6e03aebef7c0cd45b4bbb7c12763e1368b8e2246998
    ports:
      - 7575:7575
networks: {}
