services:
  transmission-openvpn:
    container_name: transmission-openvpn
    cap_add:
      - NET_ADMIN
    volumes:
      - /mnt/data/media/downloads:/media/downloads
      - /home/houdini/transmission:/config
    environment:
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=sweden
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_PASSWORD}
      - TRANSMISSION_RPC_USERNAME=perra
      - TRANSMISSION_DOWNLOAD_DIR=/media/downloads
      - TRANSMISSION_INCOMPLETE_DIR=/media/downloads/incomplete
      - TRANSMISSION_WATCH_DIR=/media/downloads
      - LOCAL_NETWORK=192.168.0.0/16
      - TZ=${TZ}
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    image: haugene/transmission-openvpn
networks: {}
