services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/houdini/kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3001:3001
    restart: unless-stopped
networks: {}
