services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/houdini/radarr:/config
      - /mnt/data/media/movies:/movies #optional
      - /mnt/data/media/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/houdini/prowlarr:/config
    ports:
      - 9696:9696  
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/houdini/sonarr:/config
      - /mnt/data/media/tv:/tv #optional
      - /mnt/data/media/downloads:/downloads #optional
    ports:
      - 8989:8989

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/houdini/bazarr:/config
      - /mnt/data/media/movies:/movies #optional
      - /mnt/data/media/tv:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /home/houdini/jellyseerr:/app/config
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/houdini/readarr:/config
      - /mnt/data/media/books:/books #optional
      - /mnt/data/media/downloads:/downloads #optional
    ports:
      - 8787:8787
    restart: unless-stopped