services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: ${TZ}
    # Volumes store your data between container upgrades
    volumes:
      - /home/houdini/wallos/db:/var/www/html/db
      - /home/houdini/wallos/logos:/var/www/html/images/uploads/logos
    restart: unless-stopped