services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/houdini/freshrss/config:/config
    ports:
      - 8120:80
    restart: unless-stopped
    labels:
      glance.name: Freshrss
      glance.icon: sh:freshrss
      glance.url: https://freshrss.w8k.site
      glance.description: RSS aggregator
networks: {}
